name: Metrics
on:
  # Schedule daily updates (at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Run workflow manually
  workflow_dispatch:
  # (Optional) Run on every push on the master branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Your Username
          user: Hardanish-Singh
          template: classic
          
          # The "Activity Overview" (Radar Chart) comes from 'activity' in base
          base: header, activity, community, repositories, metadata
          
          # The "Contributed to" (Organizations) section
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_notable_repositories: yes
          
          # Adjust this to your timezone
          config_timezone: America/Toronto
